name: Build and Release Debian Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build .deb package
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Debian Bookworm container
        run: |
          docker run --name build-container --platform linux/${{ matrix.platform }} -d -v $PWD/compile.sh:/compile.sh -v $PWD/patches:/patches -v $PWD/distrib:/distrib -w / debian:bookworm-slim sleep infinity

      - name: Run build script
        run: |
          docker exec build-container bash -c "/compile.sh"

      - name: Retrieve built .deb package
        run: |
          PACKAGE_NAME="nginx_${{ env.VERSION }}_${{ matrix.platform }}.deb"
          docker cp build-container:/build/$PACKAGE_NAME ./

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-${{ matrix.platform }}
          path: ./*.deb

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.deb
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
